// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_entries_id_ from "./routes/api/entries/[id].ts";
import * as $api_entries_index from "./routes/api/entries/index.ts";
import * as $api_projects_id_ from "./routes/api/projects/[id].ts";
import * as $api_projects_id_members_memberId_ from "./routes/api/projects/[id]/members/[memberId].ts";
import * as $api_projects_id_members_index from "./routes/api/projects/[id]/members/index.ts";
import * as $api_projects_index from "./routes/api/projects/index.ts";
import * as $api_reports_generate from "./routes/api/reports/generate.ts";
import * as $api_tasks_id_ from "./routes/api/tasks/[id].ts";
import * as $api_tasks_index from "./routes/api/tasks/index.ts";
import * as $api_templates_id_ from "./routes/api/templates/[id].ts";
import * as $api_templates_index from "./routes/api/templates/index.ts";
import * as $auth_login from "./routes/auth/login.tsx";
import * as $auth_logout from "./routes/auth/logout.ts";
import * as $auth_register from "./routes/auth/register.tsx";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $index from "./routes/index.tsx";
import * as $projects_id_index from "./routes/projects/[id]/index.tsx";
import * as $projects_id_reports from "./routes/projects/[id]/reports.tsx";
import * as $projects_id_settings from "./routes/projects/[id]/settings.tsx";
import * as $projects_id_tasks from "./routes/projects/[id]/tasks.tsx";
import * as $projects_index from "./routes/projects/index.tsx";
import * as $projects_new from "./routes/projects/new.tsx";
import * as $reports_daily from "./routes/reports/daily.tsx";
import * as $reports_monthly from "./routes/reports/monthly.tsx";
import * as $reports_weekly from "./routes/reports/weekly.tsx";
import * as $settings_templates from "./routes/settings/templates.tsx";
import * as $DashboardIsland from "./islands/DashboardIsland.tsx";
import * as $EntryForm from "./islands/EntryForm.tsx";
import * as $EntryList from "./islands/EntryList.tsx";
import * as $KanbanBoard from "./islands/KanbanBoard.tsx";
import * as $MemberManager from "./islands/MemberManager.tsx";
import * as $ProjectDeleteButton from "./islands/ProjectDeleteButton.tsx";
import * as $ProjectForm from "./islands/ProjectForm.tsx";
import * as $ProjectList from "./islands/ProjectList.tsx";
import * as $ReportView from "./islands/ReportView.tsx";
import * as $TemplateManager from "./islands/TemplateManager.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/entries/[id].ts": $api_entries_id_,
    "./routes/api/entries/index.ts": $api_entries_index,
    "./routes/api/projects/[id].ts": $api_projects_id_,
    "./routes/api/projects/[id]/members/[memberId].ts": $api_projects_id_members_memberId_,
    "./routes/api/projects/[id]/members/index.ts": $api_projects_id_members_index,
    "./routes/api/projects/index.ts": $api_projects_index,
    "./routes/api/reports/generate.ts": $api_reports_generate,
    "./routes/api/tasks/[id].ts": $api_tasks_id_,
    "./routes/api/tasks/index.ts": $api_tasks_index,
    "./routes/api/templates/[id].ts": $api_templates_id_,
    "./routes/api/templates/index.ts": $api_templates_index,
    "./routes/auth/login.tsx": $auth_login,
    "./routes/auth/logout.ts": $auth_logout,
    "./routes/auth/register.tsx": $auth_register,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/index.tsx": $index,
    "./routes/projects/[id]/index.tsx": $projects_id_index,
    "./routes/projects/[id]/reports.tsx": $projects_id_reports,
    "./routes/projects/[id]/settings.tsx": $projects_id_settings,
    "./routes/projects/[id]/tasks.tsx": $projects_id_tasks,
    "./routes/projects/index.tsx": $projects_index,
    "./routes/projects/new.tsx": $projects_new,
    "./routes/reports/daily.tsx": $reports_daily,
    "./routes/reports/monthly.tsx": $reports_monthly,
    "./routes/reports/weekly.tsx": $reports_weekly,
    "./routes/settings/templates.tsx": $settings_templates,
  },
  islands: {
    "./islands/DashboardIsland.tsx": $DashboardIsland,
    "./islands/EntryForm.tsx": $EntryForm,
    "./islands/EntryList.tsx": $EntryList,
    "./islands/KanbanBoard.tsx": $KanbanBoard,
    "./islands/MemberManager.tsx": $MemberManager,
    "./islands/ProjectDeleteButton.tsx": $ProjectDeleteButton,
    "./islands/ProjectForm.tsx": $ProjectForm,
    "./islands/ProjectList.tsx": $ProjectList,
    "./islands/ReportView.tsx": $ReportView,
    "./islands/TemplateManager.tsx": $TemplateManager,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
